### ISSUE TITLE
When receiving some new parameters, the API returns HTTP 400

### ISSUE THREAD

**Issue by etagwerker** [evanphx/benchmark.fyi#4]
Hello, 

Sorry for the dup issues. This is related to: https://github.com/evanphx/benchmark-ips/issues/82. I can close #82 and just leave this one open. 

When the API receives these parameters: 

```
["name", "central_tendency", "ips", "error", "stddev", "microseconds", "iterations", "cycles"]
```

It's returning an HTTP 400 response, because some of these keys are not present in this array: 

```
DATA_KEY = %W!name ips stddev microseconds iterations cycles!
```

This might be the simplest solution: Adding `central_tendency` and `error` to the `DATA_KEY` constant. What do you think?

**Comment by evanphx** [comment]
Merged #5 so this should be fixed now.
